version: '3.8'

services:
  task-system:
    build:
      context: ./
      dockerfile: .setup/build/Dockerfile
    container_name: "task-system"
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/go/src
    depends_on:
      - mysql
    command: [ "sh", "-c", "sleep 10 && /bin/application http" ]

  mysql:
    image: mysql:8.0
    container_name: mysql_go
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 48
      KAFKA_NUM_PARTITIONS: 3
    depends_on:
      - zookeeper
      
  task-consumer:
    build:
      context: ./
      dockerfile: .setup/build/Dockerfile
    container_name: "task-system_consumer"
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - .:/go/src
    depends_on:
      - kafka 
    command: [ "sh", "-c", "sleep 10 && /bin/application task-consumer" ]

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: always
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: "kafka:9092"
    depends_on:
      - kafka


volumes:
  mysql_data:
