// Code generated by MockGen. DO NOT EDIT.
// Source: update_task_status.usecase.go
//
// Generated by this command:
//
//	mockgen -source update_task_status.usecase.go -package domain_usecase -destination /home/fernandoviana/Documentos/Pessoal/projetos/task-system/test/mocks/domain_usecase/mock_update_task_status.usecase.go
//

// Package domain_usecase is a generated GoMock package.
package domain_usecase

import (
	context "context"
	reflect "reflect"
	dto "task-system/internal/domain/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockUpdateTaskStatusUsecaseInterface is a mock of UpdateTaskStatusUsecaseInterface interface.
type MockUpdateTaskStatusUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateTaskStatusUsecaseInterfaceMockRecorder
}

// MockUpdateTaskStatusUsecaseInterfaceMockRecorder is the mock recorder for MockUpdateTaskStatusUsecaseInterface.
type MockUpdateTaskStatusUsecaseInterfaceMockRecorder struct {
	mock *MockUpdateTaskStatusUsecaseInterface
}

// NewMockUpdateTaskStatusUsecaseInterface creates a new mock instance.
func NewMockUpdateTaskStatusUsecaseInterface(ctrl *gomock.Controller) *MockUpdateTaskStatusUsecaseInterface {
	mock := &MockUpdateTaskStatusUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockUpdateTaskStatusUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateTaskStatusUsecaseInterface) EXPECT() *MockUpdateTaskStatusUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateTaskStatusUsecaseInterface) Execute(ctx context.Context, input dto.UpdateTaskStatusDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateTaskStatusUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateTaskStatusUsecaseInterface)(nil).Execute), ctx, input)
}
