// Code generated by MockGen. DO NOT EDIT.
// Source: get_user.usecase.go
//
// Generated by this command:
//
//	mockgen -source get_user.usecase.go -package domain_usecase -destination /home/fernandoviana/Documentos/Pessoal/projetos/task-system/test/mocks/domain_usecase/mock_get_user.usecase.go
//

// Package domain_usecase is a generated GoMock package.
package domain_usecase

import (
	context "context"
	reflect "reflect"
	dto "task-system/internal/domain/dto"
	entities "task-system/internal/domain/entities"

	gomock "go.uber.org/mock/gomock"
)

// MockGetUserUsecaseInterface is a mock of GetUserUsecaseInterface interface.
type MockGetUserUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGetUserUsecaseInterfaceMockRecorder
}

// MockGetUserUsecaseInterfaceMockRecorder is the mock recorder for MockGetUserUsecaseInterface.
type MockGetUserUsecaseInterfaceMockRecorder struct {
	mock *MockGetUserUsecaseInterface
}

// NewMockGetUserUsecaseInterface creates a new mock instance.
func NewMockGetUserUsecaseInterface(ctrl *gomock.Controller) *MockGetUserUsecaseInterface {
	mock := &MockGetUserUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockGetUserUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetUserUsecaseInterface) EXPECT() *MockGetUserUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetUserUsecaseInterface) Execute(ctx context.Context, input dto.GetUserByUuidDto) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetUserUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetUserUsecaseInterface)(nil).Execute), ctx, input)
}
