// Code generated by MockGen. DO NOT EDIT.
// Source: create_user.usecase.go
//
// Generated by this command:
//
//	mockgen -source create_user.usecase.go -package domain_usecase -destination /home/fernandoviana/Documentos/Pessoal/projetos/task-system/test/mocks/domain_usecase/mock_create_user.usecase.go
//

// Package domain_usecase is a generated GoMock package.
package domain_usecase

import (
	context "context"
	reflect "reflect"
	dto "task-system/internal/domain/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockCreateUserUsecaseInterface is a mock of CreateUserUsecaseInterface interface.
type MockCreateUserUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCreateUserUsecaseInterfaceMockRecorder
}

// MockCreateUserUsecaseInterfaceMockRecorder is the mock recorder for MockCreateUserUsecaseInterface.
type MockCreateUserUsecaseInterfaceMockRecorder struct {
	mock *MockCreateUserUsecaseInterface
}

// NewMockCreateUserUsecaseInterface creates a new mock instance.
func NewMockCreateUserUsecaseInterface(ctrl *gomock.Controller) *MockCreateUserUsecaseInterface {
	mock := &MockCreateUserUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockCreateUserUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateUserUsecaseInterface) EXPECT() *MockCreateUserUsecaseInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateUserUsecaseInterface) Execute(ctx context.Context, input dto.CreateUserDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateUserUsecaseInterfaceMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateUserUsecaseInterface)(nil).Execute), ctx, input)
}
